"""
Script: run_aspen_optimization.py
Description:
    This script is used to evaluate a process configuration within Aspen Plus
    based on decision variables generated by an external optimizer.

    Workflow:
    1. Read the decision variable (temperature) from 'input.txt'.
    2. Send this variable to Aspen Plus by modifying a specific block input.
    3. Run the Aspen simulation.
    4. Extract process outputs: mass fractions, mass flow, and energy usage.
    5. Compute the total energy consumption (only positive QNET values).
    6. Return the objective value (TotalEnergy) by saving it to 'output.txt'.

    Note:
    - Aspen simulation file: Desalination.bkp
    - Decision variable used: Feed temperature of Block B14
    - Objective: Minimize energy consumption

Dependencies:
    - Python with win32com.client (for COM automation)
    - Aspen Plus installed with proper COM interface support
"""
# === Step 1: Load the libraries ===

import os 
import numpy as np
import win32com.client as win32 
import sys
# === Step 2: Launch Aspen and Load Backup File ===
aspen = win32.Dispatch('Apwn.Document')
aspen.InitFromArchive2(os.path.abspath('Desalination.bkp'))
# === Step 3: Read Decision Variable from Optimizer Output ===

# The first variable in input.txt goes for Temprature  
with open('input.txt', 'r') as F:  # Open input.txt file which our estimated values for decision varible are in it.
     l1=float(F.readline().strip()) # Optimization decision variable one
 #   l2=float(F.readline().strip()) # Optimization decision variable one
 #   l3=float(F.readline().strip()) # Optimization decision variable one

 # === Step 3: Set Variable in Aspen Model ===
aspen.Tree.FindNode("\Data\Blocks\B14\Input\TEMP").Value=l1 # Optimization decision variable one
# === Step 5: Run Aspen Simulation ===
aspen.Engine.Run2()
# === Step 6: Extract Process Stream Outputs ===
Na = (aspen.Tree.FindNode(r"\Data\Streams\S60\Output\MASSFRAC\MIXED\NA+").Value)
Cl = (aspen.Tree.FindNode("\Data\Streams\S60\Output\MASSFRAC\MIXED\CL-").Value)
BrineConc = Na + Cl
MNa = (aspen.Tree.FindNode(r"\Data\Streams\S60\Output\MASSFLOW\MIXED\NA+").Value)
MCl = (aspen.Tree.FindNode("\Data\Streams\S60\Output\MASSFLOW\MIXED\CL-").Value)
MassFlowTDS = MNa + MCl
TotalEnergy = 0
# === Step 7: Compute Total Energy Consumption (only positive QNETs) ===

blocks = [2,3,4,5,7,8,9,12,13,14,15,16,17,18,20,21,22,23,25,
          28,30,32,36,42,43,45,46,48,49,50]
variables = [
    aspen.Tree.FindNode(f"\\Data\\Blocks\\B{b}\\Output\\QNET").Value
    for b in blocks
]
#TotalEnergy =  EB2 + EB3 + EB4 + EB5 + EB7 + EB8 + EB9 + EB12 + EB13 + EB14 + EB15 + EB16 + EB17 + EB18 + EB20 + EB21 + EB22 + EB23 + EB25 + EB28 + EB30 + EB32 + EB36 + EB42 + EB43 + EB45 + EB46  + EB48 + EB49 + EB50
# Summing up only the positive variables
TotalEnergy = sum(var for var in variables if var > 0)
# === Step 8: Return Objective Value to Optimizer ===

myfile = open("output.txt","w")
myfile.write(f"{TotalEnergy:1.8f}\n") # save values of objective function.
print(TotalEnergy)
# === Exit Cleanly ===
sys.exit(0)


'''
If this part of code was not working 
blocks = [2,3,4,5,7,8,9,12,13,14,15,16,17,18,20,21,22,23,25,
          28,30,32,36,42,43,45,46,48,49,50]
variables = [
    aspen.Tree.FindNode(f"\\Data\\Blocks\\B{b}\\Output\\QNET").Value
    for b in blocks
]
Then use this below code instead 
'''

#EB2 = (aspen.Tree.FindNode("\Data\Blocks\B2\Output\QNET").Value)
#EB3 = (aspen.Tree.FindNode("\Data\Blocks\B3\Output\QNET").Value)
#EB4 = (aspen.Tree.FindNode("\Data\Blocks\B4\Output\QNET").Value)
#EB5 = (aspen.Tree.FindNode("\Data\Blocks\B5\Output\QNET").Value)
#EB7 = (aspen.Tree.FindNode("\Data\Blocks\B7\Output\QNET").Value)
#EB8 = (aspen.Tree.FindNode("\Data\Blocks\B8\Output\QNET").Value)
#EB9 = (aspen.Tree.FindNode("\Data\Blocks\B9\Output\QNET").Value)
#EB12 = (aspen.Tree.FindNode("\Data\Blocks\B12\Output\QNET").Value)
#EB13 = (aspen.Tree.FindNode("\Data\Blocks\B13\Output\QNET").Value)
#EB14 = (aspen.Tree.FindNode("\Data\Blocks\B14\Output\QNET").Value)
#EB15 = (aspen.Tree.FindNode("\Data\Blocks\B15\Output\QNET").Value)
#EB16 = (aspen.Tree.FindNode("\Data\Blocks\B16\Output\QNET").Value)
#EB17 = (aspen.Tree.FindNode("\Data\Blocks\B17\Output\QNET").Value)
#EB18 = (aspen.Tree.FindNode("\Data\Blocks\B18\Output\QNET").Value)
#EB20 = (aspen.Tree.FindNode("\Data\Blocks\B20\Output\QNET").Value)
#EB21 = (aspen.Tree.FindNode("\Data\Blocks\B21\Output\QNET").Value)
#EB22 = (aspen.Tree.FindNode("\Data\Blocks\B22\Output\QNET").Value)
#EB23 = (aspen.Tree.FindNode("\Data\Blocks\B23\Output\QNET").Value)
#EB25 = (aspen.Tree.FindNode("\Data\Blocks\B25\Output\QNET").Value)
#EB28 = (aspen.Tree.FindNode("\Data\Blocks\B28\Output\QNET").Value)
#EB30 = (aspen.Tree.FindNode("\Data\Blocks\B30\Output\QNET").Value)
#EB32 = (aspen.Tree.FindNode("\Data\Blocks\B32\Output\QNET").Value)
#EB36 = (aspen.Tree.FindNode("\Data\Blocks\B36\Output\QNET").Value)
#EB42 = (aspen.Tree.FindNode("\Data\Blocks\B42\Output\QNET").Value)
#EB43 = (aspen.Tree.FindNode("\Data\Blocks\B43\Output\QNET").Value)
#EB45 = (aspen.Tree.FindNode("\Data\Blocks\B45\Output\QNET").Value)
#EB46 = (aspen.Tree.FindNode("\Data\Blocks\B46\Output\QNET").Value)
#EB48 = (aspen.Tree.FindNode("\Data\Blocks\B48\Output\QNET").Value)
#EB49 = (aspen.Tree.FindNode("\Data\Blocks\B49\Output\QNET").Value)
#EB50 = (aspen.Tree.FindNode("\Data\Blocks\B50\Output\QNET").Value)
#variables = [EB2, EB3, EB4, EB5, EB7, EB8, EB9, EB12, EB13, EB14, EB15, EB16, EB17,
#             EB18, EB20, EB21, EB22, EB23, EB25, EB28, EB30, EB32, EB36, EB42, EB43,
#             EB45, EB46, EB48, EB49, EB50]





#============================================================================
''''
These are other decision varibles that user can explore them. 
# Pressure for the following 4 blocks have to obey this rule: B17 > B50 > B49 > B18 > .3 bar
#aspen.Tree.FindNode("\Data\Blocks\B17\Input\PRES").Value=.8   
#aspen.Tree.FindNode("\Data\Blocks\B50\Input\PRES").Value=.6
#aspen.Tree.FindNode("\Data\Blocks\B49\Input\PRES").Value=.5
#aspen.Tree.FindNode("\Data\Blocks\B18\Input\PRES").Value=.4
# Temperature for water output for B50, B49, B18
#aspen.Tree.FindNode("\Data\Blocks\B50\Input\TEMP").Value=48
#aspen.Tree.FindNode("\Data\Blocks\B49\Input\TEMP").Value=55
#aspen.Tree.FindNode("\Data\Blocks\B18\Input\TEMP").Value=60
#These parameters only affect energy usage slightly without affecting brine^^^^^
#Temp for output streams of B14, B43 Default temp: B14 = 75C    B43 = 85C
#Pressure for output streams of B14 B43  Default pres: b14 = .34bar  b43 = .5 bar
#aspen.Tree.FindNode("\Data\Blocks\B14\Input\PRES").Value=.34
#aspen.Tree.FindNode("\Data\Blocks\B43\Input\PRES").Value= l2  #Slightly increasing this pressure also decreases energy usage
'''